apiVersion: v1
kind: Service
metadata:
  name: service-logement-service
spec:
  selector:
    app: service-logement
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32303
  type: LoadBalancer